[package]
name = "maa-types"
version = "0.1.0"
edition = "2021"
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
prost = { workspace = true, optional = true }

[dev-dependencies]
serde_test = { workspace = true }
