[connection]
type = "ADB"
adb_path = "adb"
device = "emulator-5554"
config = "CompatMac"

[instance_options]
touch_mode = "MiniTouch"
deployment_with_pause = false
adb_lite_enabled = false
kill_adb_on_exit = false
